spring.application.name=HotelControl
spring.datasource.url=jdbc:postgresql://localhost:5432/HotelControl
spring.datasource.username=postgres
spring.datasource.password=erick7

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.port=8080

gemini.api.key= pegar aqui la key

gemini.model=gemini-2.5-flash